### PR TITLE
Added listing commands for tags, actors and tags having actor labels

### PR DESCRIPTION
**Pull request by cybersec-code**
Added commands for listing tags, actors and tags having actors as labels. Some fixes to the README.md file.

### CODE REVIEW

**Review by soad003 — APPROVED** [review]
I think the changes look good. Tested all the new output commands (tagpack list, actorpack list/list_address_actors).

**Nits:** 

- output csv instead of tuples (easier for post-processing)

**Review by mdragaschnig — APPROVED** [review]
I tested the new commands, looking good.

**Comment by mdragaschnig** [comment]
>     * if possible output csv instead of tuples (easier for post-processing)

+1

**Comment by soad003** [comment]
I have added a --csv option to all the new commands and harmonized the output. Will merge now.

**Pull request merged**
