### PR TITLE
Issue 59 harmonize commands

### PR DESCRIPTION
**Pull request by cybersec-code**
Changes needed to restructure the bin/tagpack-tool main commands. Three files were modified to comply with the suggestions of flake8 (bin/tagpack-tool, tagpack/tagpack.py, tagpack/tagstore.py)

### CODE REVIEW

**Comment by cybersec-code** [comment]
Did you use the version of the last commit? `confidence` command shouldn't exist anymore (now it's integrated with `taxonomy`)

**Comment by mdragaschnig** [comment]
> Did you use the version of the last commit? `confidence` command shouldn't exist anymore (now it's integrated with `taxonomy`)

No, I had a version before that commit.

Just updated and checked
* taxonomy show/insert confidence

Looking good :thumbsup:

**Review by soad003 — CHANGES_REQUESTED** [review]
I also set up a new Db and ran through the instructions in the README.md. My main issues are all related to the documentation. 

**Documentation**
- tagpack-tool validate tests/testfiles/ should be tagpack-tool tagpack validate
- same for insert
- tagstore init is also not mentioned in the README
- Ingest confidence scores (according to the code, this section is not accurate anymore)
- It also took me some time (thanks for the help @mdragaschnig) to figure out that I have to recreate my local config.yaml to add the confidence.csv to the db again. Without that, all ingest fail (some  fk errors). I think this should go in the README as well. 

**Nits**

- It looks like to shorten strings (i guess because of flake8 line to long errors)  some new string concatenations were introduced in the code. There are better ways to split strings into multiple lines in python [see](https://stackoverflow.com/questions/10112614/how-do-i-create-a-multiline-python-string-with-inline-variables)
- Command behavior is not always consistent. Sometimes commands have a "default" function like taxonomy (list) and quality (calculate) which automatically runs if invoked. Others do not like tagstore. 
- Commands like tagstore show the error message no action was requested if invoked without sub command (No action was requested). I think it would be more helpful to show the help output of the sub-command instead (if possible). In general, I would prefer the help output instead of default behavior. 

I guess the nits are open for discussion, but the changes to the README are necessary before a merge.

**Comment by cybersec-code** [comment]
Thanks for the detailed comments, maybe we can open another issue to address the consistency of the commands (i.e. the default actions).

The string concatenations were introduced to comply with the style guides recommended by flake8, and I think it's just about coding preferences. The problem with the approach in the link you suggest is that splitting strings that way will introduce undesired tabs (\t) to the resulting string (e.g. when used inside a function). I prefer the concatenation of strings either like:
```
s = "Very long"
s += " message"
```
or:
```
s = "Very long" \
    " message"
```
But again, I think it's just about preferences, feel free to change them back.

**Comment by soad003** [comment]
Thank you for the work you put in to harmonize the tools interface. 

Sure sounds good. Lets open another issue to harmonize the default actions.

Regarding the string concatenations, sure it's a preference. I was just wondering why you have chosen this particular explicit concatenation style, its verbose in my opinion. Regarding the tabs, I should have mentioned the answer I meant (see comment of Stevoisiak). My intention was to use:

```python
s =  ("Very long"
        " message")
```
Python does automatic string literal concatination [ref](https://docs.python.org/3/reference/lexical_analysis.html#string-literal-concatenation). I think it's a pretty clean and quick way to split strings in python.

**Pull request merged**
