### PR TITLE
Issue 36: Multiple header files

### PR DESCRIPTION
**Pull request by cybersec-code**
Changes in collect_tagpack_files() to support multiple header.yaml files; tests for the new functionality

### CODE REVIEW

**Review by mdragaschnig — APPROVED** [review]
Looks sensible to me.

**Comment by behas** [comment]
as discussed, it would great if headers could include other headers to avoid duplication of data points. Also consider that certain (automatically generated) tagpack files might use explicit yaml string notation to refer to headers:

`header: '!include header.yaml'`

**Comment by behas** [comment]
let's file the header references as a separate issue and close this first. @cybersec-code could you plz rebase this branch with develop and ping me when done? Then we can merge.

**Comment by cybersec-code** [comment]
I merged `develop` into this branch, so it should be updated with the last changes now

**Review by behas — APPROVED** [review]

**Pull request merged**
